<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{1f5d730c-9e96-4a11-b15c-ef2848a86c90}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb_BannerK50		: FB_BannerK50;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FB_BannerK50();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>